# Generated by Django 3.2.7 on 2021-10-07 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(max_length=1500, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('data', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('Программирование_programming', 'Программирование'), ('Математика_math', 'Математика'), ('Русский язык_rus', 'Русский язык'), ('Русская литература_ruslit', 'Русская литература'), ('Английский_eng', 'Английский')], default='math', max_length=28)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, default='https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg', upload_to='media/avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1500, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_task', to='main.task', verbose_name='Вопрос')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
    ]
