# Generated by Django 3.2.7 on 2021-10-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.CharField(choices=[('Программирование_programming', 'Программирование'), ('Математика_math', 'Математика'), ('Русский язык_rus', 'Русский язык'), ('Русская литература_ruslit', 'Русская литература'), ('Английский_eng', 'Английский')], default='math', max_length=28),
        ),
    ]
