# Generated by Django 3.2.7 on 2021-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/avatar.jpg', upload_to='media', verbose_name='Фото'),
        ),
    ]
