# Generated by Django 3.2.7 on 2021-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
