# Generated by Django 3.2.7 on 2021-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211008_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/ava.svg', upload_to='media', verbose_name='Фото'),
        ),
    ]
