# Generated by Django 3.2.7 on 2021-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210924_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
