# Generated by Django 3.2.7 on 2021-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Дураки не любят гениальных, ненавидь меня это нормально', max_length=1000, verbose_name='Описание'),
        ),
    ]
