# Generated by Django 3.2.7 on 2021-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.CharField(choices=[('programming', 'Программирование'), ('math', 'Математика'), ('rus', 'Русский язык'), ('rus_lit', 'Русская литература'), ('eng', 'Английский')], default='math', max_length=11),
        ),
    ]
