# Generated by Django 3.2.7 on 2021-10-04 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20211004_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.CharField(choices=[('Программирование_programming', 'Программирование'), ('Математика_math', 'Математика'), ('Русский язык_rus', 'Русский язык'), ('Русская литература_ruslit', 'Русская литература'), ('Английский_eng', 'Английский')], default='math', max_length=28),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
