# Generated by Django 3.2.7 on 2021-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211004_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/ava.png', upload_to='media/avatars'),
        ),
    ]
