# Generated by Django 3.2.7 on 2021-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg', upload_to='media/avatars'),
        ),
    ]
